### ISSUE TITLE
Bring Front- and Backend Services in the same network

### ISSUE THREAD

**Issue by Frederik-Roeckle** [Frederik-Roeckle/provibackend#63]
We need to do this together as we need to adjust both docker-compose files in front and backend. @FabianDus1002 

I think it should be straightforward by simply adding a network add on in the files like shown in the following discussion: https://stackoverflow.com/questions/38088279/communication-between-multiple-docker-compose-projects

**Comment by FabianDus1002** [comment]
just shoot the network name @Frederik-Roeckle
